name: Build and Deploy to Firebase
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ['web', 'admin']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install and build
        run: |
          npm install
          npm run build
        working-directory: ./${{ matrix.folder }}
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.folder }}
          path: build
        working-directory: ./${{ matrix.folder }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download web artifact
        uses: actions/download-artifact@v2
        with:
          name: web
          path: public
      - name: Download admin artifact
        uses: actions/download-artifact@v2
        with:
          name: admin
          path: public/admin
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
